#!/bin/bash

EXEC_EXPERIMENT_PATH='/root/scripts/execExperiment.sh'

MIN=20
MAX=40
OVERPROV_PERCENTAGES='' # '0 50 100 150 200 250'
for OVERPROV_PERC in ${OVERPROV_PERCENTAGES}
do
        echo 'MIN = '${MIN}' / MAX = '${MAX}' / OVERPROVISIONING PERCENTAGE = '${OVERPROV_PERC}
        ${EXEC_EXPERIMENT_PATH} ${MIN} ${MAX} ${OVERPROV_PERC}
done

MIN=15
MAX=30
OVERPROV_PERCENTAGES='' # '0 50 100 150 200 250'
for OVERPROV_PERC in ${OVERPROV_PERCENTAGES}
do      
 	echo 'MIN = '${MIN}' / MAX = '${MAX}' / OVERPROVISIONING PERCENTAGE = '${OVERPROV_PERC}
 	${EXEC_EXPERIMENT_PATH} ${MIN} ${MAX} ${OVERPROV_PERC}
done

MIN=10
MAX=20
OVERPROV_PERCENTAGES='' # '0 50 100 150 200 250'
for OVERPROV_PERC in ${OVERPROV_PERCENTAGES}
do
 	echo 'MIN = '${MIN}' / MAX = '${MAX}' / OVERPROVISIONING PERCENTAGE = '${OVERPROV_PERC}
 	${EXEC_EXPERIMENT_PATH} ${MIN} ${MAX} ${OVERPROV_PERC}
done
